spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/railwaySystem
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jqa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

